# Generated by Django 3.0 on 2022-08-18 15:51

from django.db import migrations
from oc_lettings_site.models import Profile
from django.contrib.auth.models import User
from ..models import ProfileNew

def migrate_data(apps, schema_migration):
    profiles = Profile.objects.all()
    for profile in profiles:
        profile_new = ProfileNew()
        profile_new.user = profile.user
        profile_new.favorite_city = profile.favorite_city
        profile_new.save()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
