# Generated by Django 3.0 on 2022-08-29 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20220818_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileNew',
            new_name='Profile',
        ),
    ]
