# Generated by Django 3.0 on 2022-08-18 15:19
from django.db import migrations
from copy import deepcopy


def migrate_data(apps, schema_migration):
    return

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
