# Generated by Django 3.0 on 2022-08-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20220818_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdresseNew',
            new_name='Adresse',
        ),
        migrations.RenameModel(
            old_name='LettingNew',
            new_name='Letting',
        ),
    ]
