# Generated by Django 3.0 on 2022-08-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel('Address'),
        migrations.DeleteModel('Letting'),

    ]
