# Generated by Django 3.0 on 2022-08-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0004_auto_20220829_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
